language: node_js
node_js:
  - "9.7.1"
install: npm install
script: gatsby build
deploy:
  provider: script
  script: node deploy.js
  skip_cleanup: true
cache:
  directories:
    - "node_modules"
    - ".cache"
